<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Ejercicio1.aspx.cs" Inherits="Trabajo_Practico_N6.Ejercicio1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Ejericio 1</title>
    <style type="text/css">
        .auto-style2 {
            text-align: center;
        }
        .auto-style4 {
            margin-left: 0px;
           
        }
        .auto-style5 {
            width: 100%;
        }
        .auto-style6 {
            width: 370px;
        }
        .auto-style7 {
            width: 200px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <div class="auto-style2">
                <h2 style="width:100%;text-align:center; text-decoration: underline; font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;">
                    Productos
                </h2>
                <div>
                    <br />
                    <asp:Label ID="lblmensaje" runat="server" Text=""></asp:Label>
                </div>
                <div  style="font-size: medium; text-align: center;">

                    <table class="auto-style5">
                        <tr>
                            <td class="auto-style6">&nbsp;</td>
                            <td class="auto-style7">
                <span class="auto-style"><strong style="font-size: medium; text-align: center;">
                    
                <asp:GridView ID="grdProductos" runat="server" BackColor="White" BorderColor="#336666" BorderStyle="Double" BorderWidth="3px" CellPadding="4" GridLines="Horizontal" CssClass="auto-style4" Width="600px" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" OnRowDeleting="grdProductos_RowDeleting" AllowPaging="True" AutoGenerateEditButton="True" OnPageIndexChanging="grdProductos_PageIndexChanging" OnRowCancelingEdit="grdProductos_RowCancelingEdit" OnRowEditing="grdProductos_RowEditing" OnRowUpdating="grdProductos_RowUpdating" OnSelectedIndexChanging="grdProductos_SelectedIndexChanging">
                    <Columns>
                        <asp:TemplateField HeaderText="ID Producto">
                            <EditItemTemplate>
                                <asp:Label ID="lbl_edit_id" runat="server" Text='<%# Bind("IdProducto") %>'></asp:Label>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lbl_it_id" runat="server" Text='<%# Bind("IdProducto") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Nombre Producto">
                            <EditItemTemplate>
                                <asp:TextBox ID="txt_edit_nombre" runat="server" Text='<%# Bind("NombreProducto") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lbl_it_nombre" runat="server" Text='<%# Bind("NombreProducto") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Cantidad por Unidad">
                            <EditItemTemplate>
                                <asp:TextBox ID="txt_edit_cantidad" runat="server" Text='<%# Bind("CantidadPorUnidad") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lbl_it_cantidad" runat="server" Text='<%# Bind("CantidadPorUnidad") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Precio Unitario">
                            <EditItemTemplate>
                                <asp:TextBox ID="txt_edit_pu" runat="server" Text='<%# Bind("PrecioUnidad") %>'></asp:TextBox>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="lbl_it_precio" runat="server" Text='<%# Bind("PrecioUnidad") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <FooterStyle BackColor="White" ForeColor="#333333" />
                    <HeaderStyle BackColor="#336666" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#336666" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="White" ForeColor="#333333" />
                    <SelectedRowStyle BackColor="#339966" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#F7F7F7" />
                    <SortedAscendingHeaderStyle BackColor="#487575" />
                    <SortedDescendingCellStyle BackColor="#E5E5E5" />
                    <SortedDescendingHeaderStyle BackColor="#275353" />
                </asp:GridView>
                </strong></span></td>
                            <td>&nbsp;</td>
                        </tr>
                    </table>

                </div>
                <span class="auto-style"><strong style="font-size: medium; text-align: center;">
                    
                 
                </strong></span><br />
            </div>
        </div>
        <div style="width:100%;text-align:center;">
            <asp:HyperLink ID="Hlinicio" runat="server" NavigateUrl="~/Inicio.aspx">Volver al Incio</asp:HyperLink>
        </div>
    </form>
</body>
</html>
